name: build windows version of flutter app

on:
  repository_dispatch:
    types:
      - build-windows
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
          
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: master
      
      - name: enable flutter desktop support
        run: flutter config --enable-windows-desktop
          
      - name: run build script (windows)
        run: flutter build windows
          
      - name: upload app
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build\windows\runner\Release
          retention-days: 1